### PR TITLE
Portuguese Translation

### PR DESCRIPTION
**Pull request by MaxMorais**
First, Hello from Brazil!
Second, congratulations from this amazing project!

Third my initial contribution, the Translation to Portuguese (Almost Brazilian Portuguese, but fully compatible with Portuguese of Portugal)

### CODE REVIEW

**Comment by jam-py** [comment]
Thanks, Maxwell.
Andrew

**Comment by MaxMorais** [comment]
@jam-py I noticed that there are some words that are not translated! Is there anything I can do to solve this?

**Comment by jam-py** [comment]
I have made some changes that did not include in the languge files yet. When I will do that I will ask you to translate them if you don't mide.

**Comment by MaxMorais** [comment]
Andrew take your time! When you have it done, just notify me, and I'll work on translation!
Again my respect and congratulations for this amazing project!

**Comment by dbabicwa** [comment]
Greetings from Australia!
It is really nice framework. It would be great to see more contributors with some finished projects with jam-py and some more developers chipping in.

**Pull request closed without merging**
