### PR TITLE
Docs: fix typos and clarify instructions in index, intro, and tutorial 1

### PR DESCRIPTION
**Pull request by cschreib**
Hi! I started using Jam.py today and thought it was a really nice piece of software. We may be able to use this at work to solve some of our problems. Unfortunately the documentation is sometimes a bit unclear, or the English isn't quite right. I reviewed and edited the first few sections of the docs; please see changes below.

I am happy to keep going through the whole docs, if you think this is useful.

### CODE REVIEW

**Comment by platipusica** [comment]
Hi there,
thanks!
It is very useful indeed since we concentrated more on the traction and examples. On that note, how did you find Jam? Just searching or through some other means?

Re the Docs, the official one is still missing Tips, which are here:
https://jampyapplicationbuilder.com/tips/


Hope that helps and thanks again.

**Comment by cschreib** [comment]
> It is very useful indeed since we concentrated more on the traction and examples.

Great, I'll keep going then! Do you want me to keep pushing changes to this PR, and review everything in one go, or would you prefer multiple smaller PRs?

> On that note, how did you find Jam? Just searching or through some other means?

I used a search engine looking for "sql frontend". The first result took me to [this reddit post](https://www.reddit.com/r/MSAccess/comments/svmo5f/best_free_webbased_frontend_form_for_an_sql/), which contains a post with links to the [demo](https://msaccess.pythonanywhere.com/), which finally took me to the [jampyapplicationbuilder.com](https://jampyapplicationbuilder.com/) website. From there, I downloaded the User Manual PDF. When I saw that it was just a `pip install` away from getting it running, I followed the instructions to set up a project, and they played around for a bit. IMO the ease of installation, together with it being open-source and on `pip`, was a big selling point.

> Re the Docs, the official one is still missing Tips, which are here:
> https://jampyapplicationbuilder.com/tips/

I must say that I was confused by the existence of both [jampyapplicationbuilder.com](https://jampyapplicationbuilder.com/) and [jam-py.com](https://jam-py.com/), which seem like they are both official websites but don't reference each other. Likewise, the documentation is available from multiple sources:
 - https://jam-py.com/docs/index.html
 - https://jam-py.readthedocs.io/en/latest/
 - https://jampyapplicationbuilder.com/docs/

I don't understand the relationship between these two websites.

> Hope that helps and thanks again.

Thank you guys for creating this!

**Comment by platipusica** [comment]
That was my post on reddit.

The difference is that one site is/was offering MS Access migration and the other was not. Plus live demos as needed. The Demo you accessed derived from it. 
Andrew is better positioned to advice on PR's. 
Cheers

**Comment by platipusica** [comment]
Just to loop you in, Andrew is on sick leave atm.

**Review by platipusica — APPROVED** [review]
Already on my site, so all good.

**Comment by jam-py** [comment]
Thank you very much for your work!

**Pull request merged**
